apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-server
  namespace: flask-app
  labels:
    app: flask-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-server
  template:
    metadata:
      labels:
        app: flask-server
    spec:
      containers:
        - name: flask
          image: python:3.11-slim
          ports:
            - containerPort: 5000
          command:
            - /bin/sh
            - -c
            - |
              pip install flask --quiet
              cat <<EOF > /app.py
              from flask import Flask
              app = Flask(__name__)

              @app.route('/')
              def hello():
                  return 'Hello from Flask with Istio sidecar!'

              @app.route('/health')
              def health():
                  return 'OK'

              if __name__ == '__main__':
                  app.run(host='0.0.0.0', port=5000)
              EOF
              python /app.py
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: flask-server
  namespace: flask-app
  labels:
    app: flask-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: flask-server

