---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-load-script
  namespace: sandbox-apps
data:
  load.sh: |
    #!/bin/sh
    BASE_URL="http://spring-boot-demo.sandbox-apps.svc.cluster.local"
    
    echo "Starting load generator for Spring Boot Demo..."
    echo "Target: $BASE_URL"
    
    while true; do
      # Normal traffic - Hello World (high frequency)
      for i in $(seq 1 10); do
        curl -s "$BASE_URL/" > /dev/null
        sleep 0.1
      done
      
      # Add custom tags
      for i in $(seq 1 3); do
        curl -s "$BASE_URL/add-tag" > /dev/null
        sleep 0.2
      done
      
      # Trigger errors (occasional)
      curl -s "$BASE_URL/set-error" > /dev/null
      sleep 0.5
      
      # Trace annotation spans
      for i in $(seq 1 2); do
        curl -s "$BASE_URL/trace-annotation" > /dev/null
        sleep 0.3
      done
      
      # Manual spans
      for i in $(seq 1 2); do
        curl -s "$BASE_URL/manual-span" > /dev/null
        sleep 0.3
      done
      
      # Slow endpoint (latency test)
      curl -s "$BASE_URL/slow" > /dev/null &
      
      # Health check
      curl -s "$BASE_URL/actuator/health" > /dev/null
      
      # Random delay between cycles (1-3 seconds)
      sleep $(( (RANDOM % 3) + 1 ))
      
      echo "$(date): Completed one load cycle"
    done

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-load-generator
  namespace: sandbox-apps
  labels:
    app: spring-boot-load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-load-generator
  template:
    metadata:
      labels:
        app: spring-boot-load-generator
    spec:
      containers:
        - name: load-generator
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp /scripts/load.sh /tmp/load.sh
              chmod +x /tmp/load.sh
              /tmp/load.sh
          volumeMounts:
            - name: script
              mountPath: /scripts
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
      volumes:
        - name: script
          configMap:
            name: spring-boot-load-script

